import type { Settings } from '../config/model.ts'; import { saveSettings } from '../config/store.ts'; import { normalizeUrl, apexOf } from '../shared/urls.ts'; import { isAuthorizedRoot } from '../policy/authorization.ts'; import { DiscoveryEngine } from '../engine/discovery-engine.ts'; import { A } from './ansi.ts'; import { parseKey } from './input.ts'; import { screens, type UiState, applyEvent, addLog } from './state.ts'; import { render } from './render.ts';
export async function runTui(settings:Settings):Promise<void>{
 const s:UiState={settings,screen:'dashboard',sidebar:0,selected:0,targets:[],targetInput:'',modal:'none',authorizedCandidate:'',hosts:[],routes:[],auth:[],inputs:[],findings:[],probes:[],logs:['NIGHTFALL ready. Add an authorized target with a.'],queue:[],scanning:false};
 process.stdout.write(A.alt+A.hide); if(process.stdin.setRawMode)process.stdin.setRawMode(true);process.stdin.resume();
 const redraw=()=>render(s);redraw();
 const onData=(b:Buffer)=>{const key=parseKey(b);void handle(key)};process.stdin.on('data',onData);
 const handle=async(key:string)=>{
  if(s.modal==='target'){if(key==='ESC'){s.modal='none';s.targetInput='';redraw();return}if(key==='BACKSPACE'){s.targetInput=s.targetInput.slice(0,-1);redraw();return}if(key==='ENTER'){try{const u=normalizeUrl(s.targetInput);const apex=apexOf(u.hostname);s.authorizedCandidate=apex;s.settings.authorizedRoots=Array.from(new Set([...s.settings.authorizedRoots,apex]));if(!s.targets.includes(u.toString()))s.targets.push(u.toString());addLog(s,`Authorized ${apex}.`);s.modal='none';s.targetInput='';s.screen='dashboard';s.sidebar=0;}catch{addLog(s,'Invalid URL.');}redraw();return}if(key.length===1){s.targetInput+=key;redraw();return}return}
  if(key==='q'||key==='ESC'){cleanup();return} if(key==='TAB'){s.sidebar=(s.sidebar+1)%screens.length;s.screen=screens[s.sidebar];s.selected=0;redraw();return}if(key==='SHIFT_TAB'){s.sidebar=(s.sidebar-1+screens.length)%screens.length;s.screen=screens[s.sidebar];redraw();return}if(key==='UP'||key==='k'){s.selected=Math.max(0,s.selected-1);redraw();return}if(key==='DOWN'||key==='j'){s.selected=Math.min(999,s.selected+1);redraw();return}if(key==='?'){s.screen='help';s.sidebar=screens.indexOf('help');redraw();return}if(key==='a'){s.modal='target';s.targetInput=s.targets[0]??'';redraw();return}if(key==='s'){await saveSettings(s.settings);addLog(s,`Settings saved.`);redraw();return}if(key==='d'||key==='ENTER'){if(s.scanning)return;const target=s.targets[0];if(!target){s.modal='target';redraw();return}if(!isAuthorizedRoot(target,s.settings)){addLog(s,'Target is not authorized. Add it with a.');redraw();return}s.scanning=true;s.screen='queue';s.sidebar=screens.indexOf('queue');s.hosts=[];s.routes=[];s.auth=[];s.inputs=[];s.findings=[];s.probes=[];s.logs=[];const engine=new DiscoveryEngine(s.settings,e=>{applyEvent(s,e);redraw()});void engine.scan(target).catch(e=>{addLog(s,String(e));s.scanning=false;redraw()});redraw();return}
  if(s.screen==='settings'){if(key==='+'){s.settings.concurrency=Math.min(32,s.settings.concurrency+1)}if(key==='-'){s.settings.concurrency=Math.max(1,s.settings.concurrency-1)}if(key==='['){s.settings.payloadsPerParameter=Math.max(0,s.settings.payloadsPerParameter-16)}if(key===']'){s.settings.payloadsPerParameter=Math.min(4096,s.settings.payloadsPerParameter+16)}if(key==='c'){s.settings.useCertificateTransparency=!s.settings.useCertificateTransparency}if(key==='w'){s.settings.useDnsWordlist=!s.settings.useDnsWordlist}if(key==='p'){s.settings.privateNetworks=!s.settings.privateNetworks}redraw();}
 };
 const timer=setInterval(redraw,settings.refreshMs);
 const cleanup=()=>{clearInterval(timer);process.stdin.off('data',onData);try{process.stdin.setRawMode?.(false)}catch{}process.stdout.write(A.show+A.normal);process.exit(0)};
}
